### ISSUE TITLE
color.yellow needs to be defined for the diff lexer

### ISSUE THREAD

**Issue by paaguti** [rgieseke/textadept-themes#3]
Hi,

I have tried to make the diff lexer in TextAdept "color.red and color.green-free". Unfortunately, I didn't succeed. In the process I have discovered that the diff lexer needs `color.yellow` too. I'm patching the base16 themes on my own, defining
`property['color.yellow'] = property['color.base0A']`
for dark themes and 
`property['color.yellow'] = property['color.base0D']`
for light themes. This seems to fix the issue reasonably...

Best, /PA

**Comment by rgieseke** [comment]
Thanks, I need to look into the updated Base16 generators, had wanted to do that for a while ...

If you have this patch applied already, I'd be happy about a pull request directly to this repo ...

**Comment by paaguti** [comment]
Done!
